//BUY SELL CONSTANTS
export const GET_ALL_BUY_SELL_ITEMS = "GET_ALL_BUY_SELL_ITEMS";
export const GET_SINGLE_BUY_SELL_ITEM = "GET_SINGLE_BUY_SELL_ITEM";
export const ADD_NEW_BUY_SELL_ITEM = "ADD_NEW_BUY_SELL_ITEM";
export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";

//LOST FOUND CONSTANTS
export const GET_ALL_LOST_FOUND_ITEMS = "GET_ALL_LOST_FOUND_ITEMS";
export const GET_SINGLE_LOST_FOUND_ITEM = "GET_SINGLE_LOST_FOUND_ITEM";
export const ADD_NEW_LOST_FOUND_ITEM = "ADD_NEW_LOST_FOUND_ITEM";

//REQUIREMENTS CONSTANTS
export const GET_ALL_REQUIREMENTS = "GET_ALL_REQUIREMENTS";
export const ADD_NEW_REQUIREMENT = "ADD_NEW_REQUIREMENT";

//USER CONSTANTS
export const SET_USER = "SET_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const VERIFY_EMAIL="VERIFY_EMAIL";
export const VERIFY_OTP="VERIFY_OTP"
export const SIGN_UP_ERROR="SIGN_UP_ERROR"
export const ADD_USER_DETAILS="ADD_USER_DETAILS"