//BUY SELL CONSTANTS
export const GET_ALL_BUY_SELL_ITEMS = "GET_ALL_BUY_SELL_ITEMS";
export const GET_SINGLE_BUY_SELL_ITEM = "GET_SINGLE_BUY_SELL_ITEM";
export const ADD_NEW_BUY_SELL_ITEM = "ADD_NEW_BUY_SELL_ITEM";
export const NEW_REQUEST = "NEW_REQUEST";

//LOST FOUND CONSTANTS
export const GET_ALL_LOST_FOUND_ITEMS = "GET_ALL_LOST_FOUND_ITEMS";
export const GET_SINGLE_LOST_FOUND_ITEM = "GET_SINGLE_LOST_FOUND_ITEM";
export const ADD_NEW_LOST_FOUND_ITEM = "ADD_NEW_LOST_FOUND_ITEM";

//REQUIREMENTS CONSTANTS
export const GET_ALL_REQUIREMENTS = "GET_ALL_REQUIREMENTS";
export const ADD_NEW_REQUIREMENT = "ADD_NEW_REQUIREMENT";
export const GET_MY_OWN_REQUIREMENTS="GET_MY_OWN_REQUIREMENTS";
export const EDIT_REQUIREMENT="EDIT_REQUIREMENT"
export const RESET_STATUS="RESET_STATUS";

//USER CONSTANTS
export const SET_USER = "SET_USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_OTP = "VERIFY_OTP";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const ADD_USER_DETAILS = "ADD_USER_DETAILS";
export const LOGIN_WITH_GOOGLE = "LOGIN_WITH_GOOGLE";
export const LOGIN_WITH_EMAIL = "LOGIN_WITH_EMAIL";
export const CHECKING_ERROR = "CHECKING_ERROR";
export const LOGIN_WITH_GOOGLE_ERROR = "LOGIN_WITH_GOOGLE_ERROR";
